name: CI
on:
  push:
    branches:
      - main
    tags: '*'
  pull_request:
concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ matrix.scalapack }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          # - '1.0'
          - '1.7'
          # - 'nightly'
        os:
          - ubuntu-latest
        arch:
          - x64
        scalapack:
          - libscalapack-openmpi
    env:
      JULIA_MPI_TEST_NPROCS: 2
      JULIA_MPI_TEST_BINARY: system
      DL_LOAD_PATH: /usr/lib/x86_64-linux-gnu
      JULIA_SCALAPACK_LIBRARY: ${{ matrix.scalapack }}
    steps:
      - uses: actions/checkout@v2
      - name: Install ScaLAPACK
        run: |
          sudo apt-get update -y
          sudo apt-get install -y $JULIA_SCALAPACK_LIBRARY-dev
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v1
      - name: add MPIPreferences
        shell: julia --color=yes --project=. {0}
        run: |
          using Pkg
          Pkg.add("MPIPreferences")
      - name: add MPIPreferences, use system
        shell: julia --color=yes --project=test {0}
        run: |
          using Pkg
          Pkg.add("MPIPreferences")
          using MPIPreferences
          MPIPreferences.use_system_binary(export_prefs=true)
          rm("test/Manifest.toml")
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
  # docs:
  #   name: Documentation
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: write
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: julia-actions/setup-julia@v1
  #       with:
  #         version: '1'
  #     - uses: julia-actions/julia-buildpkg@v1
  #     - uses: julia-actions/julia-docdeploy@v1
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #     - run: |
  #         julia --project=docs -e '
  #           using Documenter: DocMeta, doctest
  #           using ScaLAPACK
  #           DocMeta.setdocmeta!(ScaLAPACK, :DocTestSetup, :(using ScaLAPACK); recursive=true)
  #           doctest(ScaLAPACK)'
